# Generated by Django 4.1.7 on 2023-03-20 01:50

from django.db import migrations, models
import django.db.models.deletion
import warehouseApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(default=warehouseApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.CharField(default=warehouseApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.CharField(default=warehouseApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=warehouseApp.models.generate_primary_key, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=25, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='warehouseMedia')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.brand')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.position')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.producttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
